version: '3.2'
services:
  app:
    container_name: project-app
    image: dersonsena/php-nginx-dev
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/conf:/etc/nginx/sites-available
    environment:
      - XDEBUG_CLIENT_PORT=9000
    ports:
      - '80:80'
    networks:
      - project-network

networks:
  project-network:
    driver: bridge